### ISSUE TITLE
error running gatsby develop

### ISSUE THREAD

**Issue by bradlosh** [gatsbymanor/gatsby-theme-tessellate#1]
Hi, after loading mounting a theme and executing 'gatsby develop' I get the following error:

 ERROR  Failed to compile with 1 errors                                                               00:08:08

 error  in ./src/styles/main.scss

Module parse failed: /home/brad/myffc_gatsby/src/styles/main.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp$4.raise (/home/brad/myffc_gatsby/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/home/brad/myffc_gatsby/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/home/brad/myffc_gatsby/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/home/brad/myffc_gatsby/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/home/brad/myffc_gatsby/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/home/brad/myffc_gatsby/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/home/brad/myffc_gatsby/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/home/brad/myffc_gatsby/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/home/brad/myffc_gatsby/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/brad/myffc_gatsby/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/brad/myffc_gatsby/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/brad/myffc_gatsby/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/brad/myffc_gatsby/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)

 @ ./src/pages/index.js 43:0-30

any pointers would be greatly appreciated

**Comment by nodox** [comment]
Thats odd 😅! @bradlosh , have you considered Dockerizing your project with the error, and sending a link to your repo so we can debug this together? Happy to walk you through your first pull request! 

From the error message it seems like there might be a misplaced character in the `main.scss` file.

**Comment by nodox** [comment]
Can you send steps to reproduce? I cloned a new project, added this theme, could not reproduce this error.

**Comment by bradlosh** [comment]
good morning... thanks for getting back with me.  when I create a new project, I don't have this issue and everything works correctly.
I am going through my code to resolve.

I appreciate your response!  have a good day!
